/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CollimateState.java
 *
 * Created on 2012-9-28, 17:04:07
 */
package com.tongrui.shangweiji.ui.treatmentcontrol;

import com.tongrui.shangweiji.comm.Constant;
import com.tongrui.shangweiji.comm.CurePolar;
import java.awt.Color;

/**
 *
 * @author Administrator
 */
public class CollimateState extends javax.swing.JPanel {

    /** Creates new form CollimateState */
    public CollimateState() {
        initComponents();
        if(Constant.DEBUG_this_is_TouDao == false) {
            jLabel9.setVisible(false);
            jPanel10.setVisible(false);
        }
            

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new ColorLight(Color.GREEN, false, 18);
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new ColorLight(Color.GREEN, false, 18);
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new ColorLight(Color.GREEN, false, 18);
        jLabel6 = new javax.swing.JLabel();
        jPanel11 = new ColorLight(Color.YELLOW, false, 18);
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new ColorLight(Color.GREEN, false, 18);
        jPanel12 = new ColorLight(Color.RED, false, 18);
        jPanel13 = new ColorLight(Color.GREEN, false, 18);

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "准直体状态", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        setMinimumSize(new java.awt.Dimension(218, 350));
        setPreferredSize(new java.awt.Dimension(218, 350));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("宋体", 0, 24));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources_cn"); // NOI18N
        jLabel11.setText(bundle.getString("treatment.control.collimator.status.switch")); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel10.setText(bundle.getString("treatment.control.collimator.status.out")); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jPanel7.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel7.setMinimumSize(new java.awt.Dimension(45, 45));
        jPanel7.setPreferredSize(new java.awt.Dimension(45, 45));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel12.setText(bundle.getString("treatment.control.collimator.status.close")); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel8.setText("3#");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jPanel8.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel8.setMinimumSize(new java.awt.Dimension(45, 45));
        jPanel8.setPreferredSize(new java.awt.Dimension(45, 45));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel9.setText("4#");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jPanel9.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel9.setMinimumSize(new java.awt.Dimension(45, 45));
        jPanel9.setPreferredSize(new java.awt.Dimension(45, 45));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel6.setText("1#");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jPanel11.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel11.setMinimumSize(new java.awt.Dimension(45, 45));
        jPanel11.setPreferredSize(new java.awt.Dimension(45, 45));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel7.setText("2#");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jPanel10.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel10.setMinimumSize(new java.awt.Dimension(45, 45));
        jPanel10.setPreferredSize(new java.awt.Dimension(45, 45));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jPanel12.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel12.setMinimumSize(new java.awt.Dimension(45, 45));
        jPanel12.setPreferredSize(new java.awt.Dimension(45, 45));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jPanel13.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel13.setMinimumSize(new java.awt.Dimension(45, 45));
        jPanel13.setPreferredSize(new java.awt.Dimension(45, 45));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    public void update_date(CurePolar curePolar) {
        //wys?.address are TBD
        //1# state-light
        int state = curePolar.getCollShieldPosState_Z2();
        if(state == 0) { //stop state
            ((ColorLight)jPanel7).setClockColor(Color.green);
        } else {        //radio
            ((ColorLight)jPanel7).setClockColor(Color.yellow);
        }
        
        //2# state-light
        state = curePolar.getCollShieldPosState_Z2();
        if(state == 0) { //stop state
            ((ColorLight)jPanel8).setClockColor(Color.green);
        } else {        //radio
            ((ColorLight)jPanel8).setClockColor(Color.yellow);
        }
        
        //3# state-light
        state = curePolar.getCollShieldPosState_Z2();
        if(state == 0) { //stop state
            ((ColorLight)jPanel9).setClockColor(Color.green);
        } else {        //radio
            ((ColorLight)jPanel9).setClockColor(Color.yellow);
        }
        
        //4# state-light
        state = curePolar.getCollShieldPosState_Z2();
        if(state == 0) { //stop state
            ((ColorLight)jPanel10).setClockColor(Color.green);
        } else {        //radio
            ((ColorLight)jPanel10).setClockColor(Color.yellow);
        }
        
        //Output beam state-light
        state = curePolar.getSourceShieldPosState_T2();
        if(state == 0) { //stop state
            ((ColorLight)jPanel11).setVisible(false);
            jLabel10.setVisible(false);
        } else {        //radio
            ((ColorLight)jPanel11).setClockColor(Color.yellow);
            ((ColorLight)jPanel11).setVisible(true);
            jLabel10.setVisible(true);
        }
        
        //Alternating
        state = curePolar.getSourceShieldPosState_T2();
        if(state == 0) { //stop state
            ((ColorLight)jPanel12).setVisible(false);
            jLabel11.setVisible(false);
        } else {        //radio
            ((ColorLight)jPanel12).setClockColor(Color.red);
            ((ColorLight)jPanel12).setVisible(true);
            jLabel11.setVisible(true);
                    
        }
        
        //Closed beam
        state = curePolar.getSourceShieldPosState_T2();
        if(state == 0) { //stop state
            ((ColorLight)jPanel13).setVisible(false);
            jLabel12.setVisible(false);
        } else {        //radio
            ((ColorLight)jPanel13).setClockColor(Color.green);
            ((ColorLight)jPanel13).setVisible(true);
            jLabel12.setVisible(true);
        }
    }
}
