/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tongrui.shangweiji.ui.systemadjustment;

import com.tongrui.shangweiji.biz.ParameterTypeService;
import com.tongrui.shangweiji.biz.ServiceLocator;
import com.tongrui.shangweiji.comm.Constant;
import com.tongrui.shangweiji.comm.ControllerSvcImpl;
import com.tongrui.shangweiji.data.CatDeviceparamType;
import com.tongrui.shangweiji.data.CatDeviceparamValue;
import common.CommonMethod;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ChangeSource extends javax.swing.JFrame {
    
    private static ChangeSource manualChgSource = null;
    public static ChangeSource getInstance() {
        if(manualChgSource == null) {
            try {
                manualChgSource = new ChangeSource();
            } catch (Throwable ex) {
                Logger.getLogger(ChangeSource.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "本地数据库访问出错,请重试!");
            }
        }
        return manualChgSource;
    }

    /**
     * Creates new form ChangeSource
     */
    public ChangeSource() throws Throwable {
        initComponents();
        initCustomComponent(30);
        this.setLocationRelativeTo(null);
    }

    // custom method
    public void initCustomComponent(int num) throws Throwable {
        clearComponentFromPanel();
        addComponentToPanel(num);
        changeSourceOffset();
    }
    
    public void changeSourceOffset() throws Throwable {
        CatDeviceparamType dType = paraTypeSvc.findByName(Constant.CAT_DEVICEPARAM_TYPE_SOURCE_OFFSET);
        Iterator<CatDeviceparamValue> deviceParaValues = dType.getCatDeviceparamValues().iterator();
        while (deviceParaValues.hasNext()) {
            CatDeviceparamValue deviceParaValue = deviceParaValues.next();
            //jTextField2.setText(jRadioButton1.isSelected()?String.valueOf(deviceParaValue.getValue()):String.valueOf(deviceParaValue.getValue2()));
            jTextField2.setText(String.valueOf(deviceParaValue.getValue()));
            return;
        }
    }

    private void clearComponentFromPanel() {
        jPanel2.removeAll();
    }

    private void addComponentToPanel(int num) throws Throwable {
        CatDeviceparamType dType = paraTypeSvc.findByName(Constant.CAT_DEVICEPARAM_TYPE_SOURCE_NAME);
        Iterator<CatDeviceparamValue> deviceParaValues = dType.getCatDeviceparamValues().iterator();
        sourceBits = new ArrayList();
        while (deviceParaValues.hasNext()) {
            CatDeviceparamValue deviceParaValue = deviceParaValues.next();
            javax.swing.JLabel source = createSource(deviceParaValue.getPosition(), deviceParaValue.getValue(), deviceParaValue.getValue2());
            
            sourceBits.add(source);
            jPanel2.add(source);
        }

    }
    

    private javax.swing.JLabel createSource(float p, float v1, float v2) {
        javax.swing.JLabel source = new javax.swing.JLabel();
        source.setFont(new java.awt.Font("宋体", 0, 20));
        source.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        source.setText(String.format("%s#(%s°,%s°)", Float.valueOf(p).intValue(), v1, v2));
        source.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        return source;
    }

    private void checkCurrentSourceState(int currentSourceIndex, Color col) {
        javax.swing.JLabel source = sourceBits.get(currentSourceIndex);
        source.setOpaque(true);
        source.setBackground(col);
        //返回执行结果；       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_no1 = new javax.swing.JLabel();
        jLabel_no2 = new javax.swing.JLabel();
        jLabel_no3 = new javax.swing.JLabel();
        jLabel_no4 = new javax.swing.JLabel();
        jLabel_no5 = new javax.swing.JLabel();
        jLabel_no6 = new javax.swing.JLabel();
        jLabel_no7 = new javax.swing.JLabel();
        jLabel_no8 = new javax.swing.JLabel();
        jLabel_no9 = new javax.swing.JLabel();
        jLabel_no10 = new javax.swing.JLabel();
        jLabel_no11 = new javax.swing.JLabel();
        jLabel_no12 = new javax.swing.JLabel();
        jLabel_no13 = new javax.swing.JLabel();
        jLabel_no14 = new javax.swing.JLabel();
        jLabel_no15 = new javax.swing.JLabel();
        jLabel_no16 = new javax.swing.JLabel();
        jLabel_no17 = new javax.swing.JLabel();
        jLabel_no18 = new javax.swing.JLabel();
        jLabel_no19 = new javax.swing.JLabel();
        jLabel_no20 = new javax.swing.JLabel();
        jLabel_no21 = new javax.swing.JLabel();
        jLabel_no22 = new javax.swing.JLabel();
        jLabel_no23 = new javax.swing.JLabel();
        jLabel_no24 = new javax.swing.JLabel();
        jLabel_no25 = new javax.swing.JLabel();
        jLabel_no26 = new javax.swing.JLabel();
        jLabel_no27 = new javax.swing.JLabel();
        jLabel_no28 = new javax.swing.JLabel();
        jLabel_no29 = new javax.swing.JLabel();
        jLabel_no30 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("换源操作");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel10.setMinimumSize(new java.awt.Dimension(900, 700));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(869, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(869, 50));

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel1.setText("换源操作");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel1)
                .addContainerGap(999, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "位源编号", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(869, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(869, 300));
        jPanel2.setLayout(new java.awt.GridLayout(5, 6));

        jLabel_no1.setFont(new java.awt.Font("宋体", 0, 14));
        jLabel_no1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_no1.setText("1#(14°,90°)");
        jLabel_no1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no1);

        jLabel_no2.setText("1#(14°,90°)");
        jLabel_no2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no2);

        jLabel_no3.setText("1#(14°,90°)");
        jLabel_no3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no3);

        jLabel_no4.setText("1#(14°,90°)");
        jLabel_no4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no4);

        jLabel_no5.setText("1#(14°,90°)");
        jLabel_no5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no5);

        jLabel_no6.setText("1#(14°,90°)");
        jLabel_no6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no6);

        jLabel_no7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_no7.setText("1#(14°,90°)");
        jLabel_no7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_no7.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel2.add(jLabel_no7);

        jLabel_no8.setText("1#(14°,90°)");
        jLabel_no8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no8);

        jLabel_no9.setText("1#(14°,90°)");
        jLabel_no9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no9);

        jLabel_no10.setText("1#(14°,90°)");
        jLabel_no10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no10);

        jLabel_no11.setText("1#(14°,90°)");
        jLabel_no11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no11);

        jLabel_no12.setText("1#(14°,90°)");
        jLabel_no12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no12);

        jLabel_no13.setText("1#(14°,90°)");
        jLabel_no13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no13);

        jLabel_no14.setText("1#(14°,90°)");
        jLabel_no14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no14);

        jLabel_no15.setText("1#(14°,90°)");
        jLabel_no15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no15);

        jLabel_no16.setText("1#(14°,90°)");
        jLabel_no16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no16);

        jLabel_no17.setText("1#(14°,90°)");
        jLabel_no17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no17);

        jLabel_no18.setText("1#(14°,90°)");
        jLabel_no18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no18);

        jLabel_no19.setText("1#(14°,90°)");
        jLabel_no19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no19);

        jLabel_no20.setText("1#(14°,90°)");
        jLabel_no20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no20);

        jLabel_no21.setText("1#(14°,90°)");
        jLabel_no21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no21);

        jLabel_no22.setText("1#(14°,90°)");
        jLabel_no22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no22);

        jLabel_no23.setText("1#(14°,90°)");
        jLabel_no23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no23);

        jLabel_no24.setText("1#(14°,90°)");
        jLabel_no24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no24);

        jLabel_no25.setText("1#(14°,90°)");
        jLabel_no25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no25);

        jLabel_no26.setText("1#(14°,90°)");
        jLabel_no26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no26);

        jLabel_no27.setText("1#(14°,90°)");
        jLabel_no27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no27);

        jLabel_no28.setText("1#(14°,90°)");
        jLabel_no28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no28);

        jLabel_no29.setText("1#(14°,90°)");
        jLabel_no29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no29);

        jLabel_no30.setText("1#(14°,90°)");
        jLabel_no30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel_no30);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(jPanel2, gridBagConstraints);

        jPanel3.setMinimumSize(new java.awt.Dimension(869, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(869, 120));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "补偿设定", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("宋体", 1, 24));
        jLabel2.setText("起始源号");

        jLabel3.setFont(new java.awt.Font("宋体", 1, 24));
        jLabel3.setText("装源补偿");

        jTextField1.setFont(new java.awt.Font("宋体", 0, 24));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("10");
        jTextField1.setPreferredSize(new java.awt.Dimension(70, 25));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("宋体", 0, 24));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("3");
        jTextField2.setEnabled(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(70, 25));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("宋体", 1, 24));
        jButton1.setText("执行");
        jButton1.setPreferredSize(new java.awt.Dimension(70, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 466, 130));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()), "过程控制", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18))); // NOI18N

        jButton2.setFont(new java.awt.Font("宋体", 1, 24));
        jButton2.setText("暂停");
        jButton2.setMaximumSize(new java.awt.Dimension(70, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(70, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("宋体", 1, 24));
        jButton3.setText("执行下一个");
        jButton3.setEnabled(false);
        jButton3.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("宋体", 1, 24));
        jButton4.setText("继续");
        jButton4.setPreferredSize(new java.awt.Dimension(70, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 0, 466, 130));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 10, 0);
        jPanel10.add(jPanel3, gridBagConstraints);

        jPanel4.setMinimumSize(new java.awt.Dimension(869, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(869, 100));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "换源顺序选择", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(370, 100));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("按纬度顺序");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton2.setText("按经度顺序");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton2)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap())
        );

        jPanel5.add(jPanel9, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel5);
        jPanel5.getAccessibleContext().setAccessibleName("sourceType");

        jPanel6.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel6.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("宋体", 1, 24));
        jLabel4.setText("当前换源顺序:按纬度即:1,2,3,4,5,6,7......");
        jLabel4.setPreferredSize(new java.awt.Dimension(380, 30));
        jPanel6.add(jLabel4, "card2");

        jLabel5.setFont(new java.awt.Font("宋体", 1, 24));
        jLabel5.setText("当前换源顺序:按经度即:1,7,13,19,25......");
        jLabel5.setPreferredSize(new java.awt.Dimension(380, 30));
        jLabel5.setVisible(false);
        jPanel6.add(jLabel5, "card3");

        jPanel4.add(jPanel6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(jPanel4, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel10);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            jRadioButton1.setSelected(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(true);
        }
        //changeSourceOffset();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            jRadioButton2.setSelected(false);
            jLabel4.setVisible(true);
            jLabel5.setVisible(false);
        }
        //changeSourceOffset();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String textValue = null;
        textValue = jTextField1.getText().trim();
        boolean inputValid = CommonMethod.checkIntFromTextField(textValue, null);
        if (!inputValid || textValue.isEmpty()) {
            JOptionPane.showMessageDialog(this, "错误，请输入正整数！");
            return;
        } 
        //else
        int start = Integer.valueOf(textValue);
        currentSource = start - 1;
        if(currentSource >= 30) { //Outside of range
            currentSource = 0;
        }

        currentOffset = Float.valueOf(jTextField2.getText()).intValue();
        checkCurrentSourceState(currentSource, Color.green);
        ctrlSvcImplObj.sendCommand(Constant.MANUL_CHANGE_UNIT_k, currentSource + 1);
        System.out.println("sendCommand(Constant.MANUL_CHANGE_UNIT_k = " + (currentSource + 1));
        jButton3.setEnabled(true);
        jButton1.setEnabled(false);
        jTextField1.setEnabled(false);
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        checkCurrentSourceState(currentSource, Color.blue);
        currentSource = this.getNextSource();
        checkCurrentSourceState(currentSource, Color.green);
        ctrlSvcImplObj.sendCommand(Constant.MANUL_CHANGE_UNIT_k, currentSource + 1);
        System.out.println("sendCommand(Constant.MANUL_CHANGE_UNIT_k = " + (currentSource + 1));
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private int getNextSource() {
        System.out.println(currentSource);
        if(jRadioButton1.isSelected()) {
            currentSource++;
            if (currentSource >= 30) {
                currentSource = 0;
            }
        } else {
            currentSource = currentSource + 6;
            if(currentSource == 30) {
                currentSource = 5;
            }
            else if (currentSource > 30) {
                currentSource = currentSource%30 - 1;
            }
        }
        return currentSource;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        manualChgSource = null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeSource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeSource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeSource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeSource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ChangeSource().setVisible(true);
                } catch (Throwable ex) {
                    Logger.getLogger(ChangeSource.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "本地数据库访问出错,程序将退出!");
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_no1;
    private javax.swing.JLabel jLabel_no10;
    private javax.swing.JLabel jLabel_no11;
    private javax.swing.JLabel jLabel_no12;
    private javax.swing.JLabel jLabel_no13;
    private javax.swing.JLabel jLabel_no14;
    private javax.swing.JLabel jLabel_no15;
    private javax.swing.JLabel jLabel_no16;
    private javax.swing.JLabel jLabel_no17;
    private javax.swing.JLabel jLabel_no18;
    private javax.swing.JLabel jLabel_no19;
    private javax.swing.JLabel jLabel_no2;
    private javax.swing.JLabel jLabel_no20;
    private javax.swing.JLabel jLabel_no21;
    private javax.swing.JLabel jLabel_no22;
    private javax.swing.JLabel jLabel_no23;
    private javax.swing.JLabel jLabel_no24;
    private javax.swing.JLabel jLabel_no25;
    private javax.swing.JLabel jLabel_no26;
    private javax.swing.JLabel jLabel_no27;
    private javax.swing.JLabel jLabel_no28;
    private javax.swing.JLabel jLabel_no29;
    private javax.swing.JLabel jLabel_no3;
    private javax.swing.JLabel jLabel_no30;
    private javax.swing.JLabel jLabel_no4;
    private javax.swing.JLabel jLabel_no5;
    private javax.swing.JLabel jLabel_no6;
    private javax.swing.JLabel jLabel_no7;
    private javax.swing.JLabel jLabel_no8;
    private javax.swing.JLabel jLabel_no9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    private List<javax.swing.JLabel> sourceBits;
    private int currentSource = 0; //Range is from 0 to 29
    private int currentOffset = 0;
    private static ParameterTypeService paraTypeSvc = ServiceLocator.getParameterTypeService();
    private static ControllerSvcImpl ctrlSvcImplObj = ControllerSvcImpl.getInstance();
}
