/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SourcePartManual.java
 *
 * Created on 2012-9-24, 22:47:27
 */
package com.tongrui.shangweiji.ui.systemadjustment;

import com.tongrui.shangweiji.comm.Constant;
import com.tongrui.shangweiji.comm.ControllerSvcImpl;
import com.tongrui.shangweiji.comm.CureInfo;
import com.tongrui.shangweiji.comm.CurePolar;
import com.tongrui.shangweiji.comm.LowComputerInfo;
import common.CommonMethod;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 *
 * @author Administrator
 */
public class SourcePartManual extends javax.swing.JFrame {
    private static final Log log = LogFactory.getLog(SourcePartManual.class);
    private static SourcePartManual sourceManual = null;
    
    public static SourcePartManual getInstance() {
        if(sourceManual == null) {
            sourceManual = new SourcePartManual();
        }
        return sourceManual;
    }

    /** Creates new form SourcePartManual */
    public SourcePartManual() {
        initComponents();
        jTextField6.setEnabled(false);
        jTextField7.setEnabled(false);
        new ViewRefresh(this).start();
        this.setLocationRelativeTo(null);
    }
    
    class ViewRefresh extends Thread {

        private SourcePartManual obj = null;

        public ViewRefresh(SourcePartManual obj_) {
            this.obj = obj_;
        }

        public void run() {
                while (true) {
                    collimaterValidityCheck();
               try {
                    obj.viewUpdate();
                    Thread.sleep(500);
                } catch (InterruptedException ex) {
                    log.error(null, ex);
                }
            }
        }
    }

    private void collimaterValidityCheck() {
        if(jRadioButton2.isSelected()) {
            jRadioButton5.setEnabled(true);
            jRadioButton6.setEnabled(true);
            jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
            jRadioButton9.setEnabled(true);
            
            if(jRadioButton5.isSelected()) {
                jLabel2.setEnabled(false);
                jTextField5.setEnabled(false);
                jLabel5.setEnabled(false);
            }
            else {
                jLabel2.setEnabled(true);
                jTextField5.setEnabled(true);
                jLabel5.setEnabled(false);
            }
        }
        else {
            jRadioButton5.setEnabled(false);
            jRadioButton6.setEnabled(false);
            jRadioButton7.setEnabled(false);
            jRadioButton8.setEnabled(false);
            jRadioButton9.setEnabled(false);
            jLabel2.setEnabled(false);
            jTextField5.setEnabled(false);
            jLabel5.setEnabled(false);
        }
    }
    
    private int cycles = 0;
    private static ControllerSvcImpl ctrlSvcImplObj = ControllerSvcImpl.getInstance();
    private void viewUpdate() {
        CurePolar curePolar = ctrlSvcImplObj.getCurePolar();
        LowComputerInfo lowComputerInfo = ctrlSvcImplObj.getLowComputerInfo();
        jTextField1.setText(String.valueOf(curePolar.getSourcePosition_T2()));
        jTextField2.setText(String.valueOf(curePolar.getCollimatorPosition_Z2()));
        
        CureInfo cureInfo = ctrlSvcImplObj.getCureInfo();
        jTextField6.setText(Double.valueOf(cureInfo.getRadioTimer1()).toString());
        jTextField7.setText(Double.valueOf(cureInfo.getRadioTimer2()).toString());
        
        if (isMovingButtonValid()) {
            cycles++; //wys.TBRemoved
            if (cycles >= 5 && lowComputerInfo.getMovingState() == 0) { //Moving action is end
                restoreEnable2ValidGroup();
                releaseAllToggleButtons();
                System.out.println("Moving is end.");
            }
        } else {
            cycles = 0;
        }
        
        cureHeadState1.update_date(curePolar);
        collimateState1.update_date(curePolar);
    }
    
    boolean isMovingButtonValid() {
        return (jToggleButton4.isSelected() || jToggleButton5.isSelected() || jToggleButton6.isSelected() || jToggleButton7.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        cureHeadState1 = new com.tongrui.shangweiji.ui.treatmentcontrol.CureHeadState();
        collimateState1 = new com.tongrui.shangweiji.ui.treatmentcontrol.CollimateState();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 521));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(708, 50));

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel1.setText("射源体手动操作");
        jPanel1.add(jLabel1);

        jPanel7.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "准直器", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel5.setMaximumSize(new java.awt.Dimension(1000, 450));
        jPanel5.setMinimumSize(new java.awt.Dimension(400, 180));
        jPanel5.setPreferredSize(new java.awt.Dimension(450, 250));
        jPanel5.setLayout(null);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("关源");
        jPanel5.add(jRadioButton5);
        jRadioButton5.setBounds(9, 26, 73, 20);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton6.setText("1#");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton6);
        jRadioButton6.setBounds(9, 46, 49, 20);

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton7.setText("2#");
        jPanel5.add(jRadioButton7);
        jRadioButton7.setBounds(9, 66, 49, 20);

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton8.setText("3#");
        jPanel5.add(jRadioButton8);
        jRadioButton8.setBounds(9, 86, 49, 20);

        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton9.setText("4#");
        jPanel5.add(jRadioButton9);
        jRadioButton9.setBounds(9, 106, 49, 20);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel2.setText("设定开源时间：");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 21));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 21));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel5.add(jLabel2);
        jLabel2.setBounds(118, 26, 170, 20);

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel3.setText("定时器1：");
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 100));
        jLabel3.setMinimumSize(new java.awt.Dimension(60, 21));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel5.add(jLabel3);
        jLabel3.setBounds(168, 66, 120, 20);

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel4.setText("定时器2：");
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 100));
        jLabel4.setMinimumSize(new java.awt.Dimension(60, 21));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel5.add(jLabel4);
        jLabel4.setBounds(168, 106, 120, 20);

        jTextField5.setFont(new java.awt.Font("宋体", 0, 24));
        jTextField5.setText("5");
        jTextField5.setMaximumSize(new java.awt.Dimension(150, 40));
        jTextField5.setMinimumSize(new java.awt.Dimension(50, 25));
        jPanel5.add(jTextField5);
        jTextField5.setBounds(297, 26, 130, 30);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("宋体", 0, 24));
        jTextField6.setText("2");
        jTextField6.setMaximumSize(new java.awt.Dimension(150, 40));
        jTextField6.setMinimumSize(new java.awt.Dimension(50, 25));
        jPanel5.add(jTextField6);
        jTextField6.setBounds(300, 60, 130, 30);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("宋体", 0, 24));
        jTextField7.setText("3");
        jTextField7.setMaximumSize(new java.awt.Dimension(150, 40));
        jTextField7.setMinimumSize(new java.awt.Dimension(50, 25));
        jPanel5.add(jTextField7);
        jTextField7.setBounds(300, 100, 130, 30);

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel5.setText("秒");
        jLabel5.setMaximumSize(new java.awt.Dimension(42, 21));
        jLabel5.setMinimumSize(new java.awt.Dimension(42, 21));
        jLabel5.setPreferredSize(new java.awt.Dimension(42, 21));
        jPanel5.add(jLabel5);
        jLabel5.setBounds(445, 26, 42, 20);

        jLabel6.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel6.setText("秒");
        jLabel6.setMaximumSize(new java.awt.Dimension(42, 21));
        jLabel6.setMinimumSize(new java.awt.Dimension(42, 21));
        jLabel6.setPreferredSize(new java.awt.Dimension(42, 21));
        jPanel5.add(jLabel6);
        jLabel6.setBounds(445, 66, 42, 20);

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel7.setText("秒");
        jLabel7.setMaximumSize(new java.awt.Dimension(42, 21));
        jLabel7.setMinimumSize(new java.awt.Dimension(42, 21));
        jLabel7.setPreferredSize(new java.awt.Dimension(42, 21));
        jPanel5.add(jLabel7);
        jLabel7.setBounds(445, 106, 42, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "使能选择", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel6.setMaximumSize(new java.awt.Dimension(1000, 450));
        jPanel6.setMinimumSize(new java.awt.Dimension(400, 180));
        jPanel6.setPreferredSize(new java.awt.Dimension(450, 250));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("都不使能");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel6.add(jRadioButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton2.setText("同步使能");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel6.add(jRadioButton2, gridBagConstraints);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton4.setText("准直体使能");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel6.add(jRadioButton4, gridBagConstraints);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("宋体", 0, 24));
        jRadioButton3.setText("射源体使能");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel6.add(jRadioButton3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 255;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 10);
        jPanel2.add(jPanel6, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "状态", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 220));
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 200));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 0, 3));
        jPanel3.add(cureHeadState1);
        jPanel3.add(collimateState1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 228;
        gridBagConstraints.ipady = 404;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 10, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "手动操作", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 220));
        jPanel4.setPreferredSize(new java.awt.Dimension(450, 200));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jTextField1.setFont(new java.awt.Font("宋体", 0, 24));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jTextField1.setMaximumSize(new java.awt.Dimension(81, 23));
        jTextField1.setMinimumSize(new java.awt.Dimension(81, 23));
        jTextField1.setPreferredSize(new java.awt.Dimension(81, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jTextField1, gridBagConstraints);

        jTextField2.setFont(new java.awt.Font("宋体", 0, 24));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jTextField2.setMaximumSize(new java.awt.Dimension(81, 23));
        jTextField2.setMinimumSize(new java.awt.Dimension(81, 23));
        jTextField2.setPreferredSize(new java.awt.Dimension(81, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jTextField2, gridBagConstraints);

        jTextField3.setFont(new java.awt.Font("宋体", 0, 24));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0.0");
        jTextField3.setMaximumSize(new java.awt.Dimension(81, 23));
        jTextField3.setMinimumSize(new java.awt.Dimension(81, 23));
        jTextField3.setPreferredSize(new java.awt.Dimension(81, 23));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jTextField3, gridBagConstraints);

        jTextField4.setFont(new java.awt.Font("宋体", 0, 24));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0.0");
        jTextField4.setMaximumSize(new java.awt.Dimension(81, 23));
        jTextField4.setMinimumSize(new java.awt.Dimension(81, 23));
        jTextField4.setPreferredSize(new java.awt.Dimension(81, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jTextField4, gridBagConstraints);

        jButton8.setFont(new java.awt.Font("宋体", 0, 24));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tongrui/shangweiji/ui/image/Stop.gif"))); // NOI18N
        jButton8.setText("停止");
        jButton8.setMaximumSize(new java.awt.Dimension(200, 30));
        jButton8.setMinimumSize(new java.awt.Dimension(200, 30));
        jButton8.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jButton8, gridBagConstraints);

        jToggleButton1.setIcon(new javax.swing.ImageIcon("D:\\projects\\TongRuiShangWeiJi\\TongRuiShangWeiJi\\src\\com\\tongrui\\shangweiji\\ui\\image\\Synchronization.gif")); // NOI18N
        jToggleButton1.setEnabled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jToggleButton1, gridBagConstraints);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tongrui/shangweiji/ui/image/CircleRotate.gif"))); // NOI18N
        jToggleButton2.setEnabled(false);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jToggleButton2, gridBagConstraints);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tongrui/shangweiji/ui/image/CircleRotate.gif"))); // NOI18N
        jToggleButton3.setEnabled(false);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jToggleButton3, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel8.setText("同步转动");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel9.setText("回零：");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel10.setText("当前值(mm)：");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel4.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel11.setText("给定值(mm)：");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel4.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel12.setText("到定点：");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel4.add(jLabel12, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel14.setText("准直体转动");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("宋体", 0, 24));
        jLabel15.setText("射源体转动");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabel15, gridBagConstraints);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tongrui/shangweiji/ui/image/ToZero.gif"))); // NOI18N
        jToggleButton4.setEnabled(false);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.ipady = 8;
        jPanel4.add(jToggleButton4, gridBagConstraints);

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tongrui/shangweiji/ui/image/ToZero.gif"))); // NOI18N
        jToggleButton5.setEnabled(false);
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.ipady = 8;
        jPanel4.add(jToggleButton5, gridBagConstraints);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tongrui/shangweiji/ui/image/ToPoint.gif"))); // NOI18N
        jToggleButton6.setEnabled(false);
        jToggleButton6.setMaximumSize(new java.awt.Dimension(125, 25));
        jToggleButton6.setMinimumSize(new java.awt.Dimension(125, 25));
        jToggleButton6.setPreferredSize(new java.awt.Dimension(125, 25));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 8;
        jPanel4.add(jToggleButton6, gridBagConstraints);

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tongrui/shangweiji/ui/image/ToPoint.gif"))); // NOI18N
        jToggleButton7.setEnabled(false);
        jToggleButton7.setMaximumSize(new java.awt.Dimension(125, 25));
        jToggleButton7.setMinimumSize(new java.awt.Dimension(125, 25));
        jToggleButton7.setPreferredSize(new java.awt.Dimension(125, 25));
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 8;
        jPanel4.add(jToggleButton7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 255;
        gridBagConstraints.ipady = 402;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 10, 10);
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel7.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton2.isSelected()) { //Only pressed is valid
            jToggleButton4.setEnabled(false);
            jToggleButton6.setEnabled(false);
            ctrlSvcImplObj.sendCommand(Constant.MANUL_T2_ROTATE);
            System.out.println("sendCommand(Constant.MANUL_T2_ROTATE)");
        } else {                         //All buttons are valid
            jToggleButton4.setEnabled(true);
            jToggleButton6.setEnabled(true);
            ctrlSvcImplObj.sendCommand(Constant.MANUL_AXILES_STOP);
            System.out.println("sendCommand(Constant.MANUL_AXILES_STOP)");
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton3.isSelected()) { //Only pressed is valid
            jToggleButton5.setEnabled(false);
            jToggleButton7.setEnabled(false);
            ctrlSvcImplObj.sendCommand(Constant.MANUL_Z2_ROTATE);
            System.out.println("sendCommand(Constant.MANUL_Z2_ROTATE)");
        } else {                         //All buttons are valid
            jToggleButton5.setEnabled(true);
            jToggleButton7.setEnabled(true);
            ctrlSvcImplObj.sendCommand(Constant.MANUL_AXILES_STOP);
            System.out.println("sendCommand(Constant.MANUL_AXILES_STOP)");
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        disableAllToggleButtons();
        jToggleButton1.setEnabled(true);

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        disableAllToggleButtons();
        jToggleButton3.setEnabled(true);
        jToggleButton5.setEnabled(true);
        jToggleButton7.setEnabled(true);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        disableAllToggleButtons();
        jToggleButton2.setEnabled(true);
        jToggleButton4.setEnabled(true);
        jToggleButton6.setEnabled(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        disableAllToggleButtons();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        releaseAllToggleButtons();
        restoreEnable2ValidGroup();
        ctrlSvcImplObj.sendCommand(Constant.MANUL_AXILES_STOP);
        System.out.println("sendCommand(Constant.MENUL_AXILES_STOP)");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton4.isSelected()) { //Only pressed is valid
            jToggleButton2.setEnabled(false);
            jToggleButton6.setEnabled(false);
        } else {                         //All buttons are valid
            jToggleButton4.setSelected(true); //Keep pressed state
        }
        ctrlSvcImplObj.sendCommand(Constant.MANUL_T2_ZERO);
        System.out.println("sendCommand(Constant.MANUL_T2_ZERO)");
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton5.isSelected()) { //Only pressed is valid
            jToggleButton3.setEnabled(false);
            jToggleButton7.setEnabled(false);
        } else {                         //All buttons are valid
            jToggleButton5.setSelected(true); //Keep pressed state
        }
        ctrlSvcImplObj.sendCommand(Constant.MANUL_Z2_ZERO);
        System.out.println("sendCommand(Constant.MANUL_Z2_ZERO)");
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton6.isSelected()) { //Only pressed is valid
            jToggleButton2.setEnabled(false);
            jToggleButton4.setEnabled(false);
        } else {                         //All buttons are valid
            jToggleButton6.setSelected(true); //Keep pressed state
        }

        String st = jTextField3.getText().trim();
        boolean inputValid = CommonMethod.checkDoubleFromTextField(st,true);
        if (!inputValid) {
            return;
        }
        double value = Double.valueOf(st);
        ctrlSvcImplObj.sendCommand(Constant.MANUL_T2_POINT, value);
        System.out.println("sendCommand(Constant.MANUL_T2_POINT, " + value);
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton7.isSelected()) { //Only pressed is valid
            jToggleButton3.setEnabled(false);
            jToggleButton5.setEnabled(false);
        } else {                         //All buttons are valid
            jToggleButton7.setSelected(true); //Keep pressed state
        }

        String st = jTextField4.getText().trim();
        boolean inputValid = CommonMethod.checkDoubleFromTextField(st,true);
        if (!inputValid) {
            return;
        }
        double value = Double.valueOf(st);
        ctrlSvcImplObj.sendCommand(Constant.MANUL_Z2_POINT, value);
        System.out.println("sendCommand(Constant.MANUL_Z2_POINT, " + value);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) { //just pressed
            if (jRadioButton5.isSelected()) { //source close
                ctrlSvcImplObj.sendCommand(Constant.MANUL_T2Z2_ROTATE);
                System.out.println("sendCommand(Constant.MANUL_T2Z2_ROTATE)");
            }
            else {   //Some collimate No. is selected
                String st = jTextField5.getText().trim();
                boolean inputValid = CommonMethod.checkDoubleFromTextField(st,true);
                if (!inputValid) {
                    jToggleButton1.setSelected(false);
                    return;
                }
                double value = Double.valueOf(st);

                int colliNumber;
                if(jRadioButton9.isSelected()) colliNumber = 4;
                else if(jRadioButton8.isSelected()) colliNumber = 3;
                else if(jRadioButton7.isSelected()) colliNumber = 2;
                else colliNumber = 1;
                
                ctrlSvcImplObj.sendCommand(Constant.MANUL_T2Z2_ROTATE, value, colliNumber);
                System.out.println("sendCommand(Constant.MANUL_T2Z2_ROTATE, " + value + "; " + colliNumber);
            }
        } else {                         //just release
            ctrlSvcImplObj.sendCommand(Constant.MANUL_AXILES_STOP);
            System.out.println("sendCommand(Constant.MANUL_AXILES_STOP)");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        sourceManual = null;
    }//GEN-LAST:event_formWindowClosing

    private void disableAllToggleButtons() {
        jToggleButton1.setEnabled(false);
        jToggleButton2.setEnabled(false);
        jToggleButton3.setEnabled(false);
        jToggleButton4.setEnabled(false);
        jToggleButton5.setEnabled(false);
        jToggleButton6.setEnabled(false);
        jToggleButton7.setEnabled(false);
    }  

    private void releaseAllToggleButtons() {
        jToggleButton1.setSelected(false);
        jToggleButton2.setSelected(false);
        jToggleButton3.setSelected(false);
        jToggleButton4.setSelected(false);
        jToggleButton5.setSelected(false);
        jToggleButton6.setSelected(false);
        jToggleButton7.setSelected(false);
    }

    private void restoreEnable2ValidGroup() {
        if (buttonGroup1.getSelection() == jRadioButton2.getModel()) {
            jToggleButton1.setEnabled(true);
        } else if (buttonGroup1.getSelection() == jRadioButton3.getModel()) {
            jToggleButton2.setEnabled(true);
            jToggleButton4.setEnabled(true);
            jToggleButton6.setEnabled(true);
        } else if (buttonGroup1.getSelection() == jRadioButton4.getModel()) {
            jToggleButton3.setEnabled(true);
            jToggleButton5.setEnabled(true);
            jToggleButton7.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                if(sourceManual == null) {
                    sourceManual = getInstance();
                }
                sourceManual.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.tongrui.shangweiji.ui.treatmentcontrol.CollimateState collimateState1;
    private com.tongrui.shangweiji.ui.treatmentcontrol.CureHeadState cureHeadState1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    // End of variables declaration//GEN-END:variables
}
